[llm]
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
base_url = "https://api.deepseek.com"
model = "deepseek-chat"
prompt_writer = """请基于提供的文章内容，完成以下任务：  
1. **提炼主题**：从文章中选择一个贴近生活、具有讨论价值的主题，要求主题吸引人且适合用相声形式表现。  
2. **编写初稿**：根据主题创作一段不少于20轮对话的相声初稿，角色为小简（逗哏）和老陈（捧哏）。要求：  
   - 开场设计巧妙，能迅速吸引观众注意力；  
   - 对话幽默风趣，贴近生活；  
   - 包含至少3个明显的“包袱”，并在合适的时机抖出；  
   - 结尾要有收束感，可以是对主题的总结或升华。  

**输出格式**：  
- **topic**：明确相声的主题。  
- **dialogues**：将初稿对话以 JSON 格式输出，每轮对话作为一个对象，包含“speaker”和“content”两个字段。  

**示例输入（文章内容）**：  
最近，越来越多的人开始关注健康饮食，尤其是轻食沙拉、无糖饮料等健康食品的流行。然而，很多人对“健康食品”的理解存在误区，比如认为吃沙拉就一定健康，或者无糖饮料完全无害。与此同时，一些商家也利用消费者的心理，推出高价“健康食品”，但实际上营养价值并不高。

**示例输出（JSON 格式）**：  
```json
{
  "topic": "健康饮食的误区",
  "dialogues": [
    {
      "speaker": "小简",
      "content": "老陈，听说你最近在修仙？"
    },
    {
      "speaker": "老陈",
      "content": "修仙？我修什么仙？"
    },
    {
      "speaker": "小简",
      "content": "你不是天天吃草吗？牛吃草，你吃草，你这不就是在修仙？"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我那是吃沙拉，健康饮食！"
    },
    {
      "speaker": "小简",
      "content": "健康饮食？你那一大碗草，浇上两勺沙拉酱，热量比红烧肉还高！"
    },
    {
      "speaker": "老陈",
      "content": "啊？不能吧！沙拉酱不是健康的吗？"
    },
    {
      "speaker": "小简",
      "content": "健康？那玩意儿全是油！你以为吃草就能瘦啊？牛天天吃草，你看它瘦吗？"
    },
    {
      "speaker": "老陈",
      "content": "这……那我喝无糖饮料总行了吧？"
    },
    {
      "speaker": "小简",
      "content": "无糖饮料？那更坑！你以为无糖就是健康啊？里面全是添加剂，喝多了小心你的肝变成‘肝儿疼’！"
    },
    {
      "speaker": "老陈",
      "content": "哎哟，那我这健康饮食岂不是白折腾了？"
    },
    {
      "speaker": "小简",
      "content": "可不是嘛！你这叫‘伪健康’，光听商家忽悠，自己不动脑子。"
    },
    {
      "speaker": "老陈",
      "content": "那你说，我该怎么办？"
    },
    {
      "speaker": "小简",
      "content": "简单啊，少吃多动，别整那些花里胡哨的。你看我，每天跑步，吃饭七分饱，身体倍儿棒！"
    },
    {
      "speaker": "老陈",
      "content": "跑步？你跑几步就喘得跟风箱似的，还吹呢！"
    },
    {
      "speaker": "小简",
      "content": "那也比你这‘沙拉仙人’强！"
    },
    {
      "speaker": "老陈",
      "content": "得，我算是明白了，健康饮食不是吃草，也不是喝无糖，而是得动脑子！"
    },
    {
      "speaker": "小简",
      "content": "没错！你这脑子再不动，都快生锈了！"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我这脑子灵光着呢！"
    },
    {
      "speaker": "小简",
      "content": "灵光？那你告诉我，无糖饮料里为啥有甜味？"
    },
    {
      "speaker": "老陈",
      "content": "这……因为加了甜味剂？"
    },
    {
      "speaker": "小简",
      "content": "对啊！甜味剂是啥？化学物质！你这叫‘健康饮食’？你这叫‘化学实验’！"
    },
    {
      "speaker": "老陈",
      "content": "哎哟，我这真是被忽悠瘸了！"
    },
    {
      "speaker": "小简",
      "content": "所以啊，健康饮食得科学，别光听广告瞎吹。"
    },
    {
      "speaker": "老陈",
      "content": "有道理！那我以后还是老老实实吃饭吧，不整那些虚的了。"
    },
    {
      "speaker": "小简",
      "content": "这就对了！记住啊，健康不是吃出来的，是动出来的！"
    },
    {
      "speaker": "老陈",
      "content": "行，听你的！明天开始，我跟你一起跑步！"
    },
    {
      "speaker": "小简",
      "content": "跟我跑步？你确定？"
    },
    {
      "speaker": "老陈",
      "content": "确定啊！"
    },
    {
      "speaker": "小简",
      "content": "那你可得跟紧了，别跑两步就喊‘救命’！"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我肯定比你强！"
    },
    {
      "speaker": "小简",
      "content": "那咱们走着瞧！"
    },
    {
      "speaker": "老陈",
      "content": "走着瞧就走着瞧！"
    }
  ]
}
```
"""

prompt_reflector = """请基于提供的相声初稿，完成以下任务：  
1. **分析问题**：分析初稿中存在的问题（如开场吸引力不足、包袱设计不合理、语言不流畅、角色互动不足等）。  
2. **提出建议**：提供具体的改进建议，确保文案更幽默、更吸引人。  

**输出格式**：  
- **topic**：明确相声的主题。  
- **reflections**：将反思建议以 JSON 格式输出，包含“issue”和“suggestion”两个字段。  

**示例输入（初稿文案）**：  
```json
{
  "topic": "健康饮食的误区",
  "dialogues": [
    {
      "speaker": "小简",
      "content": "老陈，听说你最近在修仙？"
    },
    {
      "speaker": "老陈",
      "content": "修仙？我修什么仙？"
    },
    {
      "speaker": "小简",
      "content": "你不是天天吃草吗？牛吃草，你吃草，你这不就是在修仙？"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我那是吃沙拉，健康饮食！"
    },
    {
      "speaker": "小简",
      "content": "健康饮食？你那一大碗草，浇上两勺沙拉酱，热量比红烧肉还高！"
    },
    {
      "speaker": "老陈",
      "content": "啊？不能吧！沙拉酱不是健康的吗？"
    },
    {
      "speaker": "小简",
      "content": "健康？那玩意儿全是油！你以为吃草就能瘦啊？牛天天吃草，你看它瘦吗？"
    },
    {
      "speaker": "老陈",
      "content": "这……那我喝无糖饮料总行了吧？"
    },
    {
      "speaker": "小简",
      "content": "无糖饮料？那更坑！你以为无糖就是健康啊？里面全是添加剂，喝多了小心你的肝变成‘肝儿疼’！"
    },
    {
      "speaker": "老陈",
      "content": "哎哟，那我这健康饮食岂不是白折腾了？"
    },
    {
      "speaker": "小简",
      "content": "可不是嘛！你这叫‘伪健康’，光听商家忽悠，自己不动脑子。"
    },
    {
      "speaker": "老陈",
      "content": "那你说，我该怎么办？"
    },
    {
      "speaker": "小简",
      "content": "简单啊，少吃多动，别整那些花里胡哨的。你看我，每天跑步，吃饭七分饱，身体倍儿棒！"
    },
    {
      "speaker": "老陈",
      "content": "跑步？你跑几步就喘得跟风箱似的，还吹呢！"
    },
    {
      "speaker": "小简",
      "content": "那也比你这‘沙拉仙人’强！"
    },
    {
      "speaker": "老陈",
      "content": "得，我算是明白了，健康饮食不是吃草，也不是喝无糖，而是得动脑子！"
    },
    {
      "speaker": "小简",
      "content": "没错！你这脑子再不动，都快生锈了！"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我这脑子灵光着呢！"
    },
    {
      "speaker": "小简",
      "content": "灵光？那你告诉我，无糖饮料里为啥有甜味？"
    },
    {
      "speaker": "老陈",
      "content": "这……因为加了甜味剂？"
    },
    {
      "speaker": "小简",
      "content": "对啊！甜味剂是啥？化学物质！你这叫‘健康饮食’？你这叫‘化学实验’！"
    },
    {
      "speaker": "老陈",
      "content": "哎哟，我这真是被忽悠瘸了！"
    },
    {
      "speaker": "小简",
      "content": "所以啊，健康饮食得科学，别光听广告瞎吹。"
    },
    {
      "speaker": "老陈",
      "content": "有道理！那我以后还是老老实实吃饭吧，不整那些虚的了。"
    },
    {
      "speaker": "小简",
      "content": "这就对了！记住啊，健康不是吃出来的，是动出来的！"
    },
    {
      "speaker": "老陈",
      "content": "行，听你的！明天开始，我跟你一起跑步！"
    },
    {
      "speaker": "小简",
      "content": "跟我跑步？你确定？"
    },
    {
      "speaker": "老陈",
      "content": "确定啊！"
    },
    {
      "speaker": "小简",
      "content": "那你可得跟紧了，别跑两步就喊‘救命’！"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我肯定比你强！"
    },
    {
      "speaker": "小简",
      "content": "那咱们走着瞧！"
    },
    {
      "speaker": "老陈",
      "content": "走着瞧就走着瞧！"
    }
  ]
}
```

**示例输出（JSON 格式）**：  
```json
{
  "topic": "健康饮食的误区",
  "reflections": [
    {
      "issue": "开场吸引力不足",
      "suggestion": "开场可以加入更幽默的悬念，例如小简调侃老陈的饮食习惯。"
    },
    {
      "issue": "包袱设计不够密集",
      "suggestion": "在对话中增加更多笑点，例如小简用夸张的方式描述沙拉酱的热量。"
    },
    {
      "issue": "语言不够流畅",
      "suggestion": "简化部分台词，确保每句台词控制在20-25字左右。"
    },
    {
      "issue": "角色互动不足",
      "suggestion": "增加小简和老陈之间的互动，例如老陈反驳小简的观点时更幽默。"
    }
  ]
}
```
"""

prompt_rewriter = """请基于提供的相声初稿和反思建议，完成以下任务：  
1. **优化文案**：根据反思建议，优化初稿文案，确保开场更吸引人、包袱更密集、语言更流畅、角色互动更自然。  
2. **输出结果**：将优化后的文案以 JSON 格式输出，包含以下字段：  
   - **topic**：明确相声的主题。  
   - **dialogues**：将优化后的对话以 **List** 格式输出，每轮对话作为一个对象，包含“speaker”和“contents”两个字段，且 **contents** 以 **List** 形式呈现，每句台词控制在 **20-25 字** 左右。  

**示例输入（初稿文案 + 反思建议）**：  
1. **初稿文案**：
```json
{
  "topic": "健康饮食的误区",
  "dialogues": [
    {
      "speaker": "小简",
      "content": "老陈，听说你最近在修仙？"
    },
    {
      "speaker": "老陈",
      "content": "修仙？我修什么仙？"
    },
    {
      "speaker": "小简",
      "content": "你不是天天吃草吗？牛吃草，你吃草，你这不就是在修仙？"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我那是吃沙拉，健康饮食！"
    },
    {
      "speaker": "小简",
      "content": "健康饮食？你那一大碗草，浇上两勺沙拉酱，热量比红烧肉还高！"
    },
    {
      "speaker": "老陈",
      "content": "啊？不能吧！沙拉酱不是健康的吗？"
    },
    {
      "speaker": "小简",
      "content": "健康？那玩意儿全是油！你以为吃草就能瘦啊？牛天天吃草，你看它瘦吗？"
    },
    {
      "speaker": "老陈",
      "content": "这……那我喝无糖饮料总行了吧？"
    },
    {
      "speaker": "小简",
      "content": "无糖饮料？那更坑！你以为无糖就是健康啊？里面全是添加剂，喝多了小心你的肝变成‘肝儿疼’！"
    },
    {
      "speaker": "老陈",
      "content": "哎哟，那我这健康饮食岂不是白折腾了？"
    },
    {
      "speaker": "小简",
      "content": "可不是嘛！你这叫‘伪健康’，光听商家忽悠，自己不动脑子。"
    },
    {
      "speaker": "老陈",
      "content": "那你说，我该怎么办？"
    },
    {
      "speaker": "小简",
      "content": "简单啊，少吃多动，别整那些花里胡哨的。你看我，每天跑步，吃饭七分饱，身体倍儿棒！"
    },
    {
      "speaker": "老陈",
      "content": "跑步？你跑几步就喘得跟风箱似的，还吹呢！"
    },
    {
      "speaker": "小简",
      "content": "那也比你这‘沙拉仙人’强！"
    },
    {
      "speaker": "老陈",
      "content": "得，我算是明白了，健康饮食不是吃草，也不是喝无糖，而是得动脑子！"
    },
    {
      "speaker": "小简",
      "content": "没错！你这脑子再不动，都快生锈了！"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我这脑子灵光着呢！"
    },
    {
      "speaker": "小简",
      "content": "灵光？那你告诉我，无糖饮料里为啥有甜味？"
    },
    {
      "speaker": "老陈",
      "content": "这……因为加了甜味剂？"
    },
    {
      "speaker": "小简",
      "content": "对啊！甜味剂是啥？化学物质！你这叫‘健康饮食’？你这叫‘化学实验’！"
    },
    {
      "speaker": "老陈",
      "content": "哎哟，我这真是被忽悠瘸了！"
    },
    {
      "speaker": "小简",
      "content": "所以啊，健康饮食得科学，别光听广告瞎吹。"
    },
    {
      "speaker": "老陈",
      "content": "有道理！那我以后还是老老实实吃饭吧，不整那些虚的了。"
    },
    {
      "speaker": "小简",
      "content": "这就对了！记住啊，健康不是吃出来的，是动出来的！"
    },
    {
      "speaker": "老陈",
      "content": "行，听你的！明天开始，我跟你一起跑步！"
    },
    {
      "speaker": "小简",
      "content": "跟我跑步？你确定？"
    },
    {
      "speaker": "老陈",
      "content": "确定啊！"
    },
    {
      "speaker": "小简",
      "content": "那你可得跟紧了，别跑两步就喊‘救命’！"
    },
    {
      "speaker": "老陈",
      "content": "去你的！我肯定比你强！"
    },
    {
      "speaker": "小简",
      "content": "那咱们走着瞧！"
    },
    {
      "speaker": "老陈",
      "content": "走着瞧就走着瞧！"
    }
  ]
}
```

2. **反思建议**：
```json
{
  "topic": "健康饮食的误区",
  "reflections": [
    {
      "issue": "开场吸引力不足",
      "suggestion": "开场可以加入更幽默的悬念，例如小简调侃老陈的饮食习惯。"
    },
    {
      "issue": "包袱设计不够密集",
      "suggestion": "在对话中增加更多笑点，例如小简用夸张的方式描述沙拉酱的热量。"
    },
    {
      "issue": "语言不够流畅",
      "suggestion": "简化部分台词，确保每句台词控制在20-25字左右。"
    },
    {
      "issue": "角色互动不足",
      "suggestion": "增加小简和老陈之间的互动，例如老陈反驳小简的观点时更幽默。"
    }
  ]
}
```

**示例输出（JSON 格式）**：  
```json
{
  "topic": "健康饮食的误区",
  "dialogues": [
    {
      "speaker": "小简",
      "contents": [
        "老陈，听说你最近在修仙？"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "修仙？我修什么仙？"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "你不是天天吃草吗？",
        "牛吃草，你吃草，修仙呢？"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "去你的！我那是吃沙拉，健康饮食！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "健康饮食？你那沙拉酱，",
        "热量比红烧肉还高！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "啊？不能吧！沙拉酱不是健康的吗？"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "健康？那玩意儿全是油！",
        "牛吃草也没见它瘦啊！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "这……那我喝无糖饮料总行了吧？"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "无糖饮料？全是添加剂，",
        "喝多了肝儿疼！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "哎哟，那我这健康饮食岂不是白折腾了？"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "可不是嘛！你这叫‘伪健康’，",
        "光听商家忽悠！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "那你说，我该怎么办？"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "简单啊，少吃多动，",
        "别整那些花里胡哨的！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "跑步？你跑几步就喘得跟风箱似的！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "那也比你这‘沙拉仙人’强！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "得，我算是明白了，",
        "健康饮食得动脑子！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "没错！你这脑子再不动，",
        "都快生锈了！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "去你的！我这脑子灵光着呢！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "灵光？那无糖饮料为啥有甜味？"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "这……因为加了甜味剂？"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "对啊！甜味剂是化学物质，",
        "你这叫‘化学实验’！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "哎哟，我这真是被忽悠瘸了！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "所以啊，健康饮食得科学，",
        "别光听广告瞎吹！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "有道理！那我以后还是老老实实吃饭吧！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "这就对了！健康不是吃出来的，",
        "是动出来的！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "行，听你的！明天开始，",
        "我跟你一起跑步！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "跟我跑步？你确定？"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "确定啊！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "那你可得跟紧了，",
        "别跑两步就喊‘救命’！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "去你的！我肯定比你强！"
      ]
    },
    {
      "speaker": "小简",
      "contents": [
        "那咱们走着瞧！"
      ]
    },
    {
      "speaker": "老陈",
      "contents": [
        "走着瞧就走着瞧！"
      ]
    }
  ]
}
```
"""

[image]
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
model_llm = "qwen-max"
model = "wanx2.1-t2i-plus"
prompt_image = """你是一个专业的文本转图片描述助手，擅长将输入文本解析为50字以内的生动图片描述，适用于写实风格的文生图生成，并融入中国元素。

### **任务说明：**
1. **输入**：一段简短的场景或人物描述（10-20字），例如“冬日的北京胡同”。
2. **输出**：50字以内的图片描述，突出写实风格和中国元素。
3. **优先级**：
   - 核心：写实风格、50字限制。
   - 次要：文化元素、光影渲染。
4. **要求**：
   - **细节丰富**：描述场景或人物的细节，注重真实感。
   - **文化元素**：融入中国独特的文化符号（如建筑、服饰、传统物品等）。
   - **氛围渲染**：通过光影、色彩和天气渲染氛围。
   - **语言简洁**：避免抽象词汇和过度堆砌形容词。

### **示例：**
- 输入：“冬日的北京胡同”
  输出：“寒冷的冬日午后，北京胡同的老屋瓦片上积着薄霜，灰蒙的天空下，几位行人裹紧大衣匆匆走过。”
- 输入：“上海的繁华街道”
  输出：“夜幕降临，上海街头霓虹闪烁，高楼玻璃幕墙反射着五彩灯光，人群熙攘，车流不息。”
- 输入：“清晨的江南水乡”
  输出：“薄雾笼罩的江南水乡，小桥流水，几只渔船静静停泊，远处传来鸟鸣。”

### **错误示例：**
- 输入：“冬日的北京胡同”
  错误输出：“北京胡同很美，很有历史感。”（过于抽象，缺乏细节）
  改进后：“寒冷的冬日午后，北京胡同的老屋瓦片上积着薄霜，灰蒙的天空下，几位行人裹紧大衣匆匆走过。”"""
image_num = 2
image_size = "1440*1440"

[tts]
api_key = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
model = "cosyvoice-v1"
voices = ["longwan", "longcheng"]

[video]
fps = 24
font = "./fonts/DreamHanSans-W20.ttc"
opening_audio = "./demo/opening.mp3"
background_audio = "./demo/bgm.mp3"

[api]
database_url = "sqlite+aiosqlite:///tasks.db"
app_port = 8000
max_concurrent_tasks = 1
task_timeout_seconds = 600

[web]
password = "password"
